### ISSUE TITLE
Parsing error in antiSMASHed locus tags

### ISSUE THREAD

**Issue by zdk123** [ablab/nerpa#11] opened 2022-08-17 20:14 UTC
Hi, firstly, thanks for the cool tool!

However, I hit a bug that I want to report and maybe fix. It seems that the antismash json parsing is too strict about what values locus tags (contigs and ORFs) are allowed to take.

E.g. to reproduce:

```sh
wget https://antismash-db.secondarymetabolites.org/output/GCF_900103225.1/GCF_900103225.1.json
wget https://zenodo.org/record/5503984/files/pnrpdb_preprocessed.info

nerpa.py -a GCF_900103225.1.json --structures pnrpdb_preprocessed.info -o nerpa_example
```
```
  File "/Users/zkurtz/miniconda3/envs/nerpa/share/nerpa/nerpa_pipeline/NRPSPredictor_utils/json_handler.py", line 175, in handle_single_input
    "orf": int(orf_idx), "A": int(a_idx),
ValueError: invalid literal for int() with base 10: 'RS24375'
```

I am inferring from the [code/comments](https://github.com/ablab/nerpa/blob/master/src/nerpa_pipeline/NRPSPredictor_utils/json_handler.py#L253) that you assume the contig/orf names are of the form `ctg1_1` coming out of antiSMASH... However, from the example files from genbank are not generally called this and splitting on underscores may even a bit dangerous since, as far as I can tell, there is nothing in the [genbank file specs](https://ftp.ncbi.nih.gov/genbank/gbrel.txt) that would prevent a LOCUS name from having containing an underscore.

I have in mind a fix based on regex-parsing that would help generalize this package to arbitrary inputs files. I would be happy to work on this if you'd accept a PR.

**Comment by alexeigurevich** [comment] 2022-08-18 15:15
Hi, thanks for the interest in our tool!
And for a nice and quick fix as well. I just reviewed it and merged it, so I suppose the issue is solved now.

JFYI: we will soon have a new Ph.D. student working primarily on Nerpa improvement and extension, so I hope there will be more activity in the repo since September/October. Stay tuned!

**Closed as completed by alexeigurevich** 2022-08-18 15:15 UTC

**Comment by zdk123** [comment] 2022-08-18 15:58
excellent, thanks for the merge!
